# templates/secrets.yaml
{{- $chartDir := $.Files.Get "Chart.yaml" | fromYaml | dig "name" "." -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ha-validator-cluster.fullname" . }}-charon-node0-keys
type: Opaque
data:
  charon-enr-private-key: {{ $.Files.Get (printf "%s/secrets/charon/cluster/node0/charon-enr-private-key" $chartDir) | b64enc }}
  cluster-lock.json: {{ $.Files.Get (printf "%s/secrets/charon/cluster/node0/cluster-lock.json" $chartDir) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ha-validator-cluster.fullname" . }}-validator-node0-keys
type: Opaque
data:
  keystore-0.json: {{ $.Files.Get (printf "%s/secrets/charon/cluster/node0/validator_keys/keystore-0.json" $chartDir) | b64enc }}
  keystore-0.txt: {{ $.Files.Get (printf "%s/secrets/charon/cluster/node0/validator_keys/keystore-0.txt" $chartDir) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ha-validator-cluster.fullname" . }}-charon-node1-keys
type: Opaque
data:
  charon-enr-private-key: {{ $.Files.Get (printf "%s/secrets/charon/cluster/node1/charon-enr-private-key" $chartDir) | b64enc }}
  cluster-lock.json: {{ $.Files.Get (printf "%s/secrets/charon/cluster/node1/cluster-lock.json" $chartDir) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ha-validator-cluster.fullname" . }}-validator-node1-keys
type: Opaque
data:
  keystore-0.json: {{ $.Files.Get (printf "%s/secrets/charon/cluster/node1/validator_keys/keystore-0.json" $chartDir) | b64enc }}
  keystore-0.txt: {{ $.Files.Get (printf "%s/secrets/charon/cluster/node1/validator_keys/keystore-0.txt" $chartDir) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ha-validator-cluster.fullname" . }}-jwt-secret
type: Opaque
data:
  jwt.hex: {{ $.Files.Get (printf "%s/secrets/geth/jwt.hex" $chartDir) | b64enc }}